#!/usr/bin/env bash

# setxkbmap settings can be found in:
#   /usr/share/X11/xkb/rules/base.lst

if [[ $OS == 'darwin' ]]; then
  echo "Not suported on OS X" 1>&2
  exit 1
fi

current_symbols=$(setxkbmap -print | awk -F + '/xkb_symbols/ {print $0}')

if [[ $current_symbols =~ macintosh ]]; then
  setxkbmap -layout gb -model pc105 -option ctrl:nocaps
  echo 'pc keyboard layout selected'
else
  setxkbmap -layout gb -model applealu_iso -option ctrl:nocaps
  echo 'apple keyboard layout selected'
fi
